package expo.modules.passkite

import android.app.Activity
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.Promise
import com.google.android.gms.pay.Pay
import com.google.android.gms.pay.PayClient
import com.google.android.gms.pay.PayApiAvailabilityStatus

class ExpoPasskiteModule : Module() {
    private var payClient: PayClient? = null
    private var payClientActivity: Activity? = null
    private var pendingPromise: Promise? = null

    companion object {
        private const val ADD_TO_WALLET_REQUEST_CODE = 1001
    }

    private fun getPayClient(): PayClient? {
        val activity = appContext.currentActivity ?: return null

        if (payClient == null || payClientActivity !== activity) {
            payClient = Pay.getClient(activity)
            payClientActivity = activity
        }

        return payClient
    }

    private fun saveGoogleWalletJwt(jwt: String, promise: Promise) {
        val client = getPayClient()
        val activity = appContext.currentActivity

        if (client == null || activity == null) {
            promise.resolve(mapOf(
                "success" to false,
                "error" to "Google Wallet client not available"
            ))
            return
        }

        if (jwt.isBlank()) {
            promise.resolve(mapOf(
                "success" to false,
                "error" to "Google Wallet JWT must not be empty"
            ))
            return
        }

        // Store promise for result handling
        pendingPromise = promise

        try {
            client.savePasses(jwt, activity, ADD_TO_WALLET_REQUEST_CODE)
        } catch (e: Exception) {
            pendingPromise = null
            promise.resolve(mapOf(
                "success" to false,
                "error" to "Failed to add pass: ${e.message}"
            ))
        }
    }

    override fun definition() = ModuleDefinition {
        Name("ExpoPasskite")

        Events("onPassAdded", "onPassRemoved")

        OnCreate {
            getPayClient()
        }

        OnDestroy {
            payClient = null
            payClientActivity = null
        }

        // Check if passes can be added (Google Wallet available)
        AsyncFunction("canAddPasses") { promise: Promise ->
            val client = getPayClient()
            if (client == null) {
                promise.resolve(false)
                return@AsyncFunction
            }

            client.getPayApiAvailabilityStatus(PayClient.RequestType.SAVE_PASSES)
                .addOnSuccessListener { status ->
                    promise.resolve(status == PayApiAvailabilityStatus.AVAILABLE)
                }
                .addOnFailureListener {
                    promise.resolve(false)
                }
        }

        // Check if pass library is available (Google Wallet installed)
        AsyncFunction("isPassLibraryAvailable") { promise: Promise ->
            val client = getPayClient()
            if (client == null) {
                promise.resolve(false)
                return@AsyncFunction
            }

            client.getPayApiAvailabilityStatus(PayClient.RequestType.SAVE_PASSES)
                .addOnSuccessListener { status ->
                    promise.resolve(status == PayApiAvailabilityStatus.AVAILABLE)
                }
                .addOnFailureListener {
                    promise.resolve(false)
                }
        }

        // Check if a specific pass exists (not directly supported on Android)
        AsyncFunction("containsPass") { _: String, _: String ->
            // Google Wallet doesn't provide an API to check if a specific pass exists
            // Return false as we cannot determine this
            false
        }

        // Android cannot add Apple .pkpass payloads. Use addGoogleWalletJwt for Google Wallet.
        AsyncFunction("addPassToWallet") { _: String, promise: Promise ->
            promise.resolve(mapOf(
                "success" to false,
                "error" to "Android requires a Google Wallet JWT. Use addGoogleWalletJwt(jwt) or addPassToWallet({ type: 'google-wallet', jwt })."
            ))
        }

        // Add a Google Wallet pass using a signed JWT generated by your server.
        AsyncFunction("addGoogleWalletJwt") { jwt: String, promise: Promise ->
            saveGoogleWalletJwt(jwt, promise)
        }

        // Handle activity result
        OnActivityResult { _, payload ->
            if (payload.requestCode == ADD_TO_WALLET_REQUEST_CODE) {
                val promise = pendingPromise
                pendingPromise = null

                when (payload.resultCode) {
                    Activity.RESULT_OK -> {
                        promise?.resolve(mapOf(
                            "success" to true,
                            "error" to null
                        ))
                        sendEvent("onPassAdded", mapOf(
                            "passTypeIdentifier" to "",
                            "serialNumber" to ""
                        ))
                    }
                    Activity.RESULT_CANCELED -> {
                        promise?.resolve(mapOf(
                            "success" to false,
                            "error" to "User cancelled"
                        ))
                    }
                    else -> {
                        promise?.resolve(mapOf(
                            "success" to false,
                            "error" to "Unknown error occurred"
                        ))
                    }
                }
            }
        }
    }
}
